language: python

python:
  - 3.5

cache: pip

notifications:
  email:
    on_success: never
    on_failure: never

install:
  - pip install -r requirements.txt
  - pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.10.0-py3-none-any.whl
  - apt-get install graphviz
