language: python

sudo: required

python:
  - 3.5

cache: pip

notifications:
  email:
    on_success: never
    on_failure: never

install:
  - pip install tox
  - sudo apt-get install graphviz

script:
  - tox
