version: '2'
services:


  ###############################################
  #                    Files                    #
  ###############################################

  data:
    image: "alpine:3.5"
    command: tail -f /dev/null
    user: "1000"
    network_mode: "none"
    volumes:
      - .:/home/rorschach


  ###############################################
  #                 Application                 #
  ###############################################

  rorschach:
    restart: always
    depends_on:
      - data
    build:
      context: .
      dockerfile: Dockerfile
    command: python
    volumes_from:
      - data
