version: '2'
services:

  ###############################################
  #                 Application                 #
  ###############################################

  rorschach:
    #restart: always
    container_name: rorschach_system
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/rorschach
