# General settings
general:
    # List of characters to include in our dataset (the phrase CAN NOT use characters that are not defined here).
    # Separate each character with a comma with no ending comma present
    characters: A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z

    # The phrase we're trying to predict
    phrase: HELLO


# Settings for preprocessing
preprocessing:
    run: true
    shift: false
    pad: false

    # Saves
    save:
        # The entire canvas (as defined in this config file)
        raw: true

        # Save letters
        letters: true
        letters-signatures: true

        # Save letters with highlighed signature
        # TODO
        letters-illustration: true

        # Save phrase
        phrase: true
        phrase-signatures: true

        # Save words
        words: true
        words-signtures: true
        words-verification: true

    # Settings for text
    text:
        font: arial-mono
        size: 35

    # Settings for the canvas we write on (should be irrelevant)
    canvas:
        width: 1000
        height: 200

    # The signature stuff
    signature:
        height: 1
        position: 14

    # Mode to produce data set. Either normal (single chars), or words (generate using the word list)
    mode: words

    # Specific settings for the word mode (if chosen)
    word:
        number: 2

        # Avoid random words, use this hardcoded word instead. Leave empty to skip
        hardcoded: HE


# Logging
logging:
    batch_reporting: 10


# Settings for predicting
predicting:
    run: true
    epochs: 10
    batch_size: 20

    # Class to lazy load for the prediction
    predictor: nets.lstm.RNNPredictor
