# General settings
general:
    # List of characters to include in our dataset (the phrase CAN NOT use characters that are not defined here).
    # Separate each character with a comma with no ending comma present
    characters: A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z

    # The phrase we're trying to predict
    phrase: HELLO


# Settings for preprocessing
preprocessing:
    run: true
    save: false
    shift: false
    pad: false

    # Settings for text
    text:
        font: arial-mono
        size: 35

    # Settings for the canvas we write on (should be irrelevant)
    canvas:
        width: 1000
        height: 200

    # The signature stuff
    signature:
        height: 1
        position: 14

    # Mode to produce data set. Either normal (single chars), or words (generate using the word list)
    mode: words

    # Specific settings for the word mode (if chosen)
    word:
        number: 2


# Logging
logging:
    batch_reporting: 10


# Settings for predicting
predicting:
    run: true
    epochs: 10

    # Class to lazy load for the prediction
    predictor: nets.lstm.RNNPredictor
