##################################################################
#                          General                               #
##################################################################

general:
    # List of characters to include in our dataset (the phrase CAN NOT use characters that are not defined here).
    # Separate each character with a comma with no ending comma present
    characters: A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z

##################################################################
#                          Logging                               #
##################################################################

logging:
    batch_reporting: 10

##################################################################
#                       Preprocessing                            #
##################################################################

preprocessing:
    run: true

    # Remove all earlier data on each run
    wipe: true

    # Turn on to handle identical signatures as one
    unique-signatures: true

    # Saves
    save:
        # The entire canvas (as defined in this config file)
        raw: true

        # Save letters
        letters: true
        letters-signatures: true
        letters-illustration: true

        # Training set
        training: true
        training-signtures: true

        # Test set
        test: true
        test-signatures: true

    # Settings for text
    text:
        font: arial-mono
        size: 35

    # Settings for the canvas we write on (should be irrelevant)
    canvas:
        width: 300
        height: 50

    # The signature stuff
    signature:
        height: 1
        position: 14

    # Various settings for the input
    input:
        # Maximum length of a word to classify
        max-length: 10

    # Training set
    training-set:
        size: 4000

    # Test set
    test-set:
        size: 400

##################################################################
#                       Transformation                           #
##################################################################

transformation:
    run: true

    # List of transformations to apply, in order
    handlers:
        # Initialize the labels
        - transformation.handlers.initializers.LabelInitializeHandler

        # Translate individual bits to string representations
        - transformation.handlers.input.ConcatenateBinaryDataHandler

        # Pad the input sequence to fit the longest sequence
        - transformation.handlers.input.PadHandler

        # Translate text sequences into integers (B -> 0, 6W -> 5, ...)
        - transformation.handlers.input.IntegerifyStringSequenceHandler

        # Translate the label text to corresponding integer ids (A -> 1, D -> 4, ...)
        - transformation.handlers.output.IntegerifyLabelHandler

        # Swap inputs and labels
        - transformation.handlers.finalize.SwapHandler

##################################################################
#                         Predicting                             #
##################################################################

predicting:
    run: true
    epochs: 10
    batch_size: 20

    # Class to lazy load for the prediction
    predictor: prediction.tensorflow.networks.sequence.EmbeddingRNNSeq2SeqPredictor
